=== ITU-T-SG11-Q8/Q.4102/oms/OMS/org/apache/ibatis/builder/xml/mybatis-3-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT configuration (properties?, settings?, typeAliases?, typeHandlers?, objectFactory?, objectWrapperFactory?, plugins?, environments?, mappers?)>

<!ELEMENT properties (property*)>
<!ATTLIST properties
resource CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT settings (setting+)>

<!ELEMENT setting EMPTY>
<!ATTLIST setting
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
type CDATA #REQUIRED
alias CDATA #IMPLIED
>

<!ELEMENT typeHandlers (typeHandler+)>

<!ELEMENT typeHandler EMPTY>
<!ATTLIST typeHandler
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
handler CDATA #REQUIRED
>

<!ELEMENT objectFactory (property*)>
<!ATTLIST objectFactory
type CDATA #REQUIRED
>

<!ELEMENT objectWrapperFactory (property*)>
<!ATTLIST objectWrapperFactory
type CDATA #REQUIRED
>

<!ELEMENT plugins (plugin+)>

<!ELEMENT plugin (property*)>
<!ATTLIST plugin
interceptor CDATA #REQUIRED
>

<!ELEMENT environments (environment+)>
<!ATTLIST environments
default CDATA #REQUIRED
>

<!ELEMENT environment (transactionManager,dataSource)>
<!ATTLIST environment
id CDATA #REQUIRED
>

<!ELEMENT transactionManager (property*)>
<!ATTLIST transactionManager
type CDATA #REQUIRED
>

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource
type CDATA #REQUIRED
>

<!ELEMENT mappers (mapper+)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
resource CDATA #IMPLIED
url CDATA #IMPLIED
>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/database/SqlMapConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN" "http://mybatis.org/dtd/mybatis-3-config.dtd">

<configuration>
	<!-- CREATE SCHEMA `uprep` ; -->
	<environments default="development_integrated">
		
		<environment id="default_uprep_datasource">
			<transactionManager type="JDBC" />
			<dataSource type="POOLED">
				<property name="driver" value="com.mysql.jdbc.Driver" />
				<property name="url" value="jdbc:mysql://localhost:3306/uprep" />
				<property name="username" value="root" />
				<property name="password" value="root" />
				<property name="defaultAutoCommit" value="false" />
				<property name="poolMaximumActiveConnections" value="1000"/>  
				<property name="poolMaximumIdleConnections" value="20"/>  
				<property name="poolMaximumCheckoutTime" value="20000"/>  
				<property name="poolPingEnabled" value="true"/>  
				<property name="poolPingQuery" value="select 1 from dual"/>
				<property name="poolPingConnectionsNotUsedFor" value="3600"/>  
				<property name="poolTimeToWait" value="30000"/>  
			</dataSource>
		</environment>
		
		<environment id="uprep_datasource">
			<transactionManager type="JDBC" />
			<dataSource type="POOLED">
				<property name="driver" value="com.mysql.jdbc.Driver" />
				<property name="url" value="${mysql.db.url}" />
				<property name="username" value="${mysql.db.username}" />
				<property name="password" value="${mysql.db.password}" />
				<property name="defaultAutoCommit" value="false" />
				<property name="poolMaximumActiveConnections" value="1000"/>  
				<property name="poolMaximumIdleConnections" value="20"/>  
				<property name="poolMaximumCheckoutTime" value="20000"/>  
				<property name="poolPingEnabled" value="true"/>  
				<property name="poolPingQuery" value="select 1"/>
				<property name="poolPingConnectionsNotUsedFor" value="3600"/>  
				<property name="poolTimeToWait" value="30000"/>
			</dataSource>
		</environment>
		
	</environments>
</configuration>
