=== ITU-T-SG11-Q8/Q.4102/oms/OMS/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
xmlns:fo CDATA #IMPLIED
namespace CDATA #IMPLIED
>

<!ELEMENT cache-ref EMPTY>
<!ATTLIST cache-ref
namespace CDATA #REQUIRED
>

<!ELEMENT cache (property*)>
<!ATTLIST cache
type CDATA #IMPLIED
eviction CDATA #IMPLIED
flushInterval CDATA #IMPLIED
size CDATA #IMPLIED
readOnly CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
>

<!ELEMENT constructor (idArg*,arg*)>

<!ELEMENT id EMPTY>
<!ATTLIST id
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT idArg EMPTY>
<!ATTLIST idArg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST collection
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
ofType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST association
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT discriminator (case+)>
<!ATTLIST discriminator
column CDATA #IMPLIED
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST case
value CDATA #REQUIRED
resultMap CDATA #IMPLIED 
resultType CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
fetchSize CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
useCache (true|false) #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
>

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST sql
id CDATA #REQUIRED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== ITU-T-SG11-Q8/Q.4102/network/mp2p/moms/OMS/kr/re/etri/uprep/shared/mapper/AuthUsersMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_AUTH_USER" parameterType="hashmap" resultType="hashmap">
		SELECT  OVERLAY_NETWORK_ID,                                        
		        USER_ID,
		        UPDATED_AT
		FROM     
				uprep_auth_users
		<where>
			<trim prefixOverrides="AND">
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="USER_ID != null">
					AND USER_ID = #{USER_ID}
				</if>
			</trim>
		</where>
	</select>
	
	<insert id="INSERT_AUTH_USER" parameterType="hashmap">
		INSERT INTO uprep_auth_users
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        OVERLAY_NETWORK_ID,
	   			USER_ID,
	   			UPDATED_AT                                       
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
	   			#{OVERLAY_NETWORK_ID},                                        
		        #{USER_ID},
		        now()
			</trim>
		ON 
			DUPLICATE KEY 
		UPDATE
			UPDATED_AT = now()
	</insert>
	
	<delete id="DELETE_AUTH_USER" parameterType="hashmap" >
		DELETE FROM 
			uprep_auth_users 
		<where>
			<trim prefixOverrides="AND">
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="USER_ID != null">
					AND USER_ID = #{USER_ID}
				</if>
			</trim>
		</where>
	</delete>
	
	<delete id="DELETE_ALL_AUTH_USER" parameterType="hashmap" >
		DELETE FROM 
			uprep_auth_users 
		<where>
			<if test="OVERLAY_ID_LIST != null">
			OVERLAY_NETWORK_ID IN
				<foreach collection="OVERLAY_ID_LIST" item="item" separator="," open="(" close=")">
				    #{item}
				</foreach>
			</if>
		</where>
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/network/mp2p/moms/OMS/kr/re/etri/uprep/shared/mapper/FileHashMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_FILE_HASH" parameterType="hashmap" resultType="hashmap">
		SELECT  FILE_ID,
	   			HASH_INDEX, 
	   			CHANNEL_ID,                                       
		        HASH_VALUE,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT                                  
		FROM     
				uprep_file_hash
		<where>
			<trim prefixOverrides="AND">
				<if test="FILE_ID != null">
					AND FILE_ID = #{FILE_ID}
				</if>
				<if test="HASH_INDEX != null">
					AND HASH_INDEX = #{HASH_INDEX}
				</if>
			</trim>
		</where>
	</select>
	
	<insert id="INSERT_FILE_HASH" parameterType="hashmap">
		INSERT INTO uprep_file_hash
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        FILE_ID,
	   			HASH_INDEX,
	   			CHANNEL_ID,                                        
		        HASH_VALUE,
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{FILE_ID},
	   			#{HASH_INDEX},
	   			#{CHANNEL_ID},                                        
		        #{HASH_VALUE},
		        now()
			</trim>
		ON 
			DUPLICATE KEY 
		UPDATE
			HASH_VALUE = #{HASH_VALUE} , 
			CREATED_AT = now()
	</insert>
	
	<update id ="UPDATE_FILE_HASH" parameterType="hashmap">
		UPDATE uprep_file_hash
		SET    
		       <if test="HASH_VALUE != null">HASH_VALUE = #{HASH_VALUE},</if>
		       CREATED_AT = now()
		WHERE  
			FILE_ID = #{FILE_ID}
		AND 
			HASH_INDEX = #{HASH_INDEX}
	</update>
	
	<delete id="DELETE_FILE_HASH" parameterType="hashmap" >
		DELETE FROM 
			uprep_file_hash
		<where>
			<trim prefixOverrides="AND">
				<if test="FILE_ID != null">
					AND FILE_ID = #{FILE_ID}
				</if>
				<if test="HASH_INDEX != null">
					AND HASH_INDEX = #{HASH_INDEX}
				</if>
				<if test="CHANNEL_ID != null">
					AND CHANNEL_ID = #{CHANNEL_ID}
				</if>
			</trim>
		</where> 
	</delete>
	
	<delete id="DELETE_ALL_FILE_HASH" parameterType="hashmap" >
		DELETE FROM 
			uprep_file_hash
		<where>
			<if test="CHANNEL_ID_LIST != null">
			CHANNEL_ID IN
				<foreach collection="CHANNEL_ID_LIST" item="item" separator="," open="(" close=")">
				    #{item}
				</foreach>
			</if>
		</where>
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/mapper/ReservationMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_RESERVATION" parameterType="hashmap" resultType="hashmap">
		SELECT  VIRTUAL_PEER_ID,
		        REQUESTER_PEER_ID,
				OVERLAY_NETWORK_ID,
				RESOURCE_ID,
		        INDEX_URL,
		        OMS_ADDRESS,
		        PIECE_SIZE,
		        ACTION_TYPE,
		        STORAGE_SIZE,
	   			MAX_UP_BW,
	   			MAX_DN_BW,
	   			MAX_NUM_CONNECTION,
	   			TIMEOUT,
	   			MAX_TRAFFIC,
	   			NUM_OF_SEEDER,
	   			COMPLETED,
	   			EXPIRES,
	   			NETWORK_IP,
	   			NETWORK_PORT,
	   			LINK,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT,
		        DATE_FORMAT(UPDATED_AT, '%Y-%m-%d %H:%i:%s') UPDATED_AT                                  
		FROM     
				uprep_cache_server_reservation
		<where>
			<trim prefixOverrides="AND">
				<if test="VIRTUAL_PEER_ID != null">
					AND VIRTUAL_PEER_ID = #{VIRTUAL_PEER_ID}
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="REQUESTER_PEER_ID != null">
					AND REQUESTER_PEER_ID = #{REQUESTER_PEER_ID}
				</if>
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="CS_URL != null">
					AND RESOURCE_ID IN
					(SELECT RESOURCE_ID FROM uprep_cache_server_registration WHERE CS_URL LIKE CONCAT('%',#{CS_URL},'%'))
				</if>
				<!-- <if test="RESOURCE_ID_LIST != null">
					AND RESOURCE_ID IN
					<foreach collection="RESOURCE_ID_LIST" item="item" separator="," open="(" close=")">
					    #{item}
					</foreach>
				</if> -->
			</trim>
		</where>
	</select>
	
	<select id="SELECT_LAST_INSERT_RESERVATION_ID" parameterType="hashmap" resultType="hashmap">
		SELECT  
				VIRTUAL_PEER_ID
		FROM     
				uprep_cache_server_reservation
		ORDER BY 
				CREATED_AT DESC 
		LIMIT 1
	</select>
	
	<insert id="INSERT_RESERVATION" parameterType="hashmap">
		INSERT INTO uprep_cache_server_reservation
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
				VIRTUAL_PEER_ID,
		        REQUESTER_PEER_ID,
				OVERLAY_NETWORK_ID,
				<if test="RESOURCE_ID != null">RESOURCE_ID,</if>
		        INDEX_URL,
		        <if test="OMS_ADDRESS != null">OMS_ADDRESS,</if>
		        PIECE_SIZE,
		        ACTION_TYPE,
		        <if test="STORAGE_SIZE != null">STORAGE_SIZE,</if>
	   			<if test="MAX_UP_BW != null">MAX_UP_BW,</if>
	   			<if test="MAX_DN_BW != null">MAX_DN_BW,</if>
	   			<if test="MAX_NUM_CONNECTION != null">MAX_NUM_CONNECTION,</if>
	   			<if test="TIMEOUT != null">TIMEOUT,</if>
	   			<if test="MAX_TRAFFIC != null">MAX_TRAFFIC,</if>
	   			<if test="NUM_OF_SEEDER != null">NUM_OF_SEEDER,</if>
	   			<if test="COMPLETED != null">COMPLETED,</if>
	   			<if test="EXPIRES != null">EXPIRES,</if>
	   			<if test="NETWORK_IP != null">NETWORK_IP,</if>
	   			<if test="NETWORK_PORT != null">NETWORK_PORT,</if>
	   			<if test="LINK != null">LINK,</if>
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{VIRTUAL_PEER_ID},
		        #{REQUESTER_PEER_ID},
				#{OVERLAY_NETWORK_ID},
				<if test="RESOURCE_ID != null">#{RESOURCE_ID},</if>
		        #{INDEX_URL},
		        <if test="OMS_ADDRESS != null">#{OMS_ADDRESS},</if>
		        #{PIECE_SIZE},
		        #{ACTION_TYPE},
		        <if test="STORAGE_SIZE != null">#{STORAGE_SIZE},</if>
	   			<if test="MAX_UP_BW != null">#{MAX_UP_BW},</if>
	   			<if test="MAX_DN_BW != null">#{MAX_DN_BW},</if>
	   			<if test="MAX_NUM_CONNECTION != null">#{MAX_NUM_CONNECTION},</if>
	   			<if test="TIMEOUT != null">#{TIMEOUT},</if>
	   			<if test="MAX_TRAFFIC != null">#{MAX_TRAFFIC},</if>
	   			<if test="NUM_OF_SEEDER != null">#{NUM_OF_SEEDER},</if>
	   			<if test="COMPLETED != null">#{COMPLETED},</if>
	   			<if test="EXPIRES != null">#{EXPIRES},</if>
	   			<if test="NETWORK_IP != null">#{NETWORK_IP},</if>
	   			<if test="NETWORK_PORT != null">#{NETWORK_PORT},</if>
	   			<if test="LINK != null">#{LINK},</if>
		        now()
			</trim>
	</insert>
	
	<update id ="UPDATE_RESERVATION" parameterType="hashmap">
		UPDATE uprep_cache_server_reservation
		SET    
			<if test="STORAGE_SIZE != null"> STORAGE_SIZE = #{STORAGE_SIZE} ,</if> 
			<if test="STORAGE_SIZE != null"> MAX_UP_BW = #{MAX_UP_BW} ,</if>
			<if test="STORAGE_SIZE != null"> MAX_DN_BW = #{MAX_DN_BW} ,</if>
			<if test="STORAGE_SIZE != null"> MAX_NUM_CONNECTION = #{MAX_NUM_CONNECTION} ,</if>
			<if test="STORAGE_SIZE != null"> TIMEOUT = #{TIMEOUT},</if>
	   		<if test="STORAGE_SIZE != null"> MAX_TRAFFIC = #{MAX_TRAFFIC},</if>
	   		<if test="NUM_OF_SEEDER != null"> NUM_OF_SEEDER = #{NUM_OF_SEEDER},</if> 
	   		<if test="COMPLETED != null"> COMPLETED = #{COMPLETED},</if> 
			UPDATED_AT = now()
		WHERE  
			VIRTUAL_PEER_ID = #{VIRTUAL_PEER_ID}
	</update>
	
	<delete id="DELETE_RESERVATION" parameterType="hashmap" >
		DELETE FROM 
			uprep_cache_server_reservation
		<where>
			<trim prefixOverrides="AND">
				<if test="VIRTUAL_PEER_ID != null">
					AND VIRTUAL_PEER_ID = #{VIRTUAL_PEER_ID}
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="REQUESTER_PEER_ID != null">
					AND REQUESTER_PEER_ID = #{REQUESTER_PEER_ID}
				</if>
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
			</trim>
		</where> 
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/mapper/RegistrationMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_REGISTRATION" parameterType="hashmap" resultType="hashmap">
		SELECT  RESOURCE_ID,
				CS_URL,
				OMS_URL,
	   			TYPE,                                        
		        IP_ADDRESS,
		        PORT,
		        EXPIRES,
		        STORAGE_SIZE,
		        MAX_UP_BW,
	            MAX_DN_BW,
		        MAX_NUM_CONNECTION,
		        MAX_NUM_OVERLAY_NETWORK,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT,
		        DATE_FORMAT(UPDATED_AT, '%Y-%m-%d %H:%i:%s') UPDATED_AT                                  
		FROM     
				uprep_cache_server_registration
		<where>
			<trim prefixOverrides="AND">
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="TYPE != null">
					AND TYPE = #{TYPE}
				</if>
				<if test="OMS_URL != null">
					AND OMS_URL LIKE CONCAT('%',#{OMS_URL},'%')
				</if>
				<if test="CS_URL != null">
					AND CS_URL LIKE CONCAT('%',#{CS_URL},'%')
				</if>
			</trim>
		</where>
	</select>
	
	<insert id="INSERT_REGISTRATION" parameterType="hashmap">
		INSERT INTO uprep_cache_server_registration
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        RESOURCE_ID,
		        <if test="CS_URL != null">CS_URL,</if>
		        OMS_URL,
	   			TYPE,                                        
		        <if test="IP_ADDRESS != null">IP_ADDRESS,</if>
		        <if test="PORT != null">PORT,</if>
		        <if test="EXPIRES != null">EXPIRES,</if>
		        <if test="STORAGE_SIZE != null">STORAGE_SIZE,</if>
		        MAX_UP_BW,
	            MAX_DN_BW,
		        MAX_NUM_CONNECTION,
		        MAX_NUM_OVERLAY_NETWORK,
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{RESOURCE_ID},
		        <if test="CS_URL != null">#{CS_URL},</if>
		        #{OMS_URL},
	   			#{TYPE},                                        
		        <if test="IP_ADDRESS != null">#{IP_ADDRESS},</if>
		        <if test="PORT != null">#{PORT},</if>
		        <if test="EXPIRES != null">#{EXPIRES},</if>
		        <if test="STORAGE_SIZE != null">#{STORAGE_SIZE},</if>
		        #{MAX_UP_BW},
	            #{MAX_DN_BW},
		        #{MAX_NUM_CONNECTION},
		        #{MAX_NUM_OVERLAY_NETWORK},
		        now()
			</trim>
		ON 
			DUPLICATE KEY 
		UPDATE
			TYPE = #{TYPE} , 
			EXPIRES = #{EXPIRES} ,
			<if test="STORAGE_SIZE != null"> STORAGE_SIZE = #{STORAGE_SIZE} ,</if> 
			MAX_UP_BW = #{MAX_UP_BW} ,
			MAX_DN_BW = #{MAX_DN_BW} ,
			MAX_NUM_CONNECTION = #{MAX_NUM_CONNECTION} ,
			MAX_NUM_OVERLAY_NETWORK = #{MAX_NUM_OVERLAY_NETWORK} ,
			UPDATED_AT = now()
	</insert>
	
	<update id ="UPDATE_REGISTRATION" parameterType="hashmap">
		UPDATE uprep_cache_server_registration
		SET    
	        TYPE = #{TYPE} , 
			EXPIRES = #{EXPIRES} ,
			<if test="STORAGE_SIZE != null"> STORAGE_SIZE = #{STORAGE_SIZE} ,</if> 
			MAX_UP_BW = #{MAX_UP_BW} ,
			MAX_DN_BW = #{MAX_DN_BW} ,
			MAX_NUM_CONNECTION = #{MAX_NUM_CONNECTION} ,
			MAX_NUM_OVERLAY_NETWORK = #{MAX_NUM_OVERLAY_NETWORK} ,
			UPDATED_AT = now()
		WHERE  
			RESOURCE_ID = #{RESOURCE_ID}
	</update>
	
	<delete id="DELETE_REGISTRATION" parameterType="hashmap" >
		DELETE FROM 
			uprep_cache_server_registration
		<where>
			<trim prefixOverrides="AND">
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="OMS_URL != null">
					AND OMS_URL LIKE CONCAT('%',#{OMS_URL},'%')
				</if>
			</trim>
		</where> 
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/mapper/ChannelMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_OMS_ADDRESS" parameterType="hashmap" resultType="hashmap">
		SELECT  
				DISTINCT OMS_ADDRESS
		FROM     
				uprep_channel
		WHERE 
				OMS_ADDRESS IS NOT NULL
	</select>
	
	<select id="SELECT_CHANNEL" parameterType="hashmap" resultType="hashmap">
		SELECT  CHANNEL_ID,
	   			VERSION,                                        
		        TITLE,
		        OWNER_ID,
		        OVERLAY_NETWORK_ID,
                OMS_ADDRESS,
                CLOSED,
                AUTH_KEY,
                PIECE_SIZE,
                CONTENT_TYPE,
                CONTENT_SIZE,
                PIECE_NUM,
                THUMBNAIL_PATH,
                IMAGE_PATH,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT,
		        DATE_FORMAT(UPDATED_AT, '%Y-%m-%d %H:%i:%s') UPDATED_AT          
		                                           
		FROM     
				uprep_channel
		<where>
			<trim prefixOverrides="AND">
				<if test="CHANNEL_ID != null">
					AND CHANNEL_ID = #{CHANNEL_ID}
				</if>
				<if test="OWNER_ID != null">
					AND OWNER_ID LIKE CONCAT('%',#{OWNER_ID},'%')
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="TITLE != null">
					AND TITLE LIKE CONCAT('%',#{TITLE},'%')
				</if>
				<if test="OMS_ADDRESS != null">
					AND OMS_ADDRESS LIKE CONCAT('%',#{OMS_ADDRESS},'%')
				</if>
			</trim>
		</where>
	</select>
	
	<insert id="INSERT_CHANNEL" parameterType="hashmap">
		INSERT INTO uprep_channel
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        CHANNEL_ID,
	   			VERSION,                                        
		        TITLE,
		        OWNER_ID,
		        OVERLAY_NETWORK_ID,
                OMS_ADDRESS,
                CLOSED,
                <if test="AUTH_KEY != null">AUTH_KEY,</if>  
                PIECE_SIZE,
                CONTENT_TYPE,
                <if test="CONTENT_SIZE != null">CONTENT_SIZE,</if>  
                <if test="PIECE_NUM != null">PIECE_NUM,</if>  
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{CHANNEL_ID},
	   			#{VERSION},                                        
		        #{TITLE},
		        #{OWNER_ID},
		        #{OVERLAY_NETWORK_ID},
		        #{OMS_ADDRESS},
		        #{CLOSED},
		        <if test="AUTH_KEY != null">#{AUTH_KEY},</if>  
		        #{PIECE_SIZE},
		        #{CONTENT_TYPE},
		        <if test="CONTENT_SIZE != null">#{CONTENT_SIZE},</if>  
		        <if test="PIECE_NUM != null">#{PIECE_NUM},</if> 
		        now()
			</trim>
	</insert>
	
	<update id ="UPDATE_CHANNEL" parameterType="hashmap">
		UPDATE uprep_channel
		SET    
		       <if test="VERSION != null">VERSION = #{VERSION},</if>
		       <if test="TITLE != null">TITLE = #{TITLE},</if>
  		       <if test="CLOSED != null">CLOSED = #{CLOSED},</if>
  		       <if test="CONTENT_SIZE != null">CONTENT_SIZE = #{CONTENT_SIZE},</if>
  		       <if test="PIECE_NUM != null">PIECE_NUM = #{PIECE_NUM},</if>
		       <if test="THUMBNAIL_PATH != null">THUMBNAIL_PATH = #{THUMBNAIL_PATH},</if>
		       <if test="IMAGE_PATH != null">IMAGE_PATH = #{IMAGE_PATH},</if>
		       UPDATED_AT = now()
		WHERE  
			CHANNEL_ID = #{CHANNEL_ID}
	</update>
	
	<delete id="DELETE_CHANNEL" parameterType="hashmap" >
		DELETE FROM 
			uprep_channel
		WHERE  
			CHANNEL_ID = #{CHANNEL_ID}
	</delete>
	
	<delete id="DELETE_ALL_CHANNEL" parameterType="hashmap" >
		DELETE FROM 
			uprep_channel
		<where>
			<trim prefixOverrides="AND">
				<if test="CHANNEL_ID != null">
					AND CHANNEL_ID = #{CHANNEL_ID}
				</if>
				<if test="OWNER_ID != null">
					AND OWNER_ID LIKE CONCAT('%',#{OWNER_ID},'%')
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="OMS_ADDRESS != null">
					AND OMS_ADDRESS LIKE CONCAT('%',#{OMS_ADDRESS},'%')
				</if>
			</trim>
		</where>
	</delete>
</mapper>
