=== ITU-T-SG11-Q8/Q.4102/oms/OMS/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
xmlns:fo CDATA #IMPLIED
namespace CDATA #IMPLIED
>

<!ELEMENT cache-ref EMPTY>
<!ATTLIST cache-ref
namespace CDATA #REQUIRED
>

<!ELEMENT cache (property*)>
<!ATTLIST cache
type CDATA #IMPLIED
eviction CDATA #IMPLIED
flushInterval CDATA #IMPLIED
size CDATA #IMPLIED
readOnly CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
>

<!ELEMENT constructor (idArg*,arg*)>

<!ELEMENT id EMPTY>
<!ATTLIST id
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT idArg EMPTY>
<!ATTLIST idArg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST collection
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
ofType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST association
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT discriminator (case+)>
<!ATTLIST discriminator
column CDATA #IMPLIED
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST case
value CDATA #REQUIRED
resultMap CDATA #IMPLIED 
resultType CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
fetchSize CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
useCache (true|false) #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
>

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST sql
id CDATA #REQUIRED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== ITU-T-SG11-Q8/Q.4102/network/mp2p/moms/OMS/kr/re/etri/uprep/shared/mapper/ResourceAllocationMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_RESOURCE_ALLOCATION" parameterType="hashmap" resultType="hashmap">
		SELECT  INDEX_URL,
	   			REQUESTER_PEER_ID,                                        
		        ACTION_TYPE,
		        NOTIFICATION_ADDRESS,
		        STORAGE_SIZE,
		        MAX_UP_BW,
		        MAX_DN_BW,
		        MAX_NUM_CONNECTION,
		        TIMEOUT,
		        MAX_TRAFFIC,
		        NUM_OF_SEEDER,
		        COMPLETE,
		        RESOURCE_ID,
		        VIRTUAL_PEER_ID,
		        RELAY_SESSION_ID,
		        EXPIRES,
		        NETWORK_IP,
		        NETWORK_PORT,
		        LINK,
		        OVERLAY_NETWORK_ID,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT ,
		        DATE_FORMAT(UPDATED_AT, '%Y-%m-%d %H:%i:%s') UPDATED_AT                                   
		FROM     
				uprep_resource_allocation
		<where>
			<trim prefixOverrides="AND">
				<if test="REQUESTER_PEER_ID != null">
					AND REQUESTER_PEER_ID = #{REQUESTER_PEER_ID}
				</if>
				<if test="ACTION_TYPE != null">
					AND ACTION_TYPE = #{ACTION_TYPE}
				</if>
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="VIRTUAL_PEER_ID != null">
					AND VIRTUAL_PEER_ID = #{VIRTUAL_PEER_ID}
				</if>
				<if test="RELAY_SESSION_ID != null">
					AND RELAY_SESSION_ID = #{RELAY_SESSION_ID}
				</if>
				<if test="INDEX_URL != null">
					AND INDEX_URL LIKE CONCAT('%',#{INDEX_URL},'%')
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
			</trim>
		</where>
	</select>
	
	<insert id="INSERT_RESOURCE_ALLOCATION" parameterType="hashmap">
		INSERT INTO uprep_resource_allocation
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        <if test="INDEX_URL != null">INDEX_URL,</if>
	   			REQUESTER_PEER_ID,                                        
		        ACTION_TYPE,
		        <if test="NOTIFICATION_ADDRESS != null">NOTIFICATION_ADDRESS,</if>
		        <if test="STORAGE_SIZE != null">STORAGE_SIZE,</if>
		        <if test="MAX_UP_BW != null">MAX_UP_BW,</if>
		        <if test="MAX_DN_BW != null">MAX_DN_BW,</if>
		        <if test="MAX_NUM_CONNECTION != null">MAX_NUM_CONNECTION,</if>
		        <if test="TIMEOUT != null">TIMEOUT,</if>
		        <if test="MAX_TRAFFIC != null">MAX_TRAFFIC,</if>
		        <if test="NUM_OF_SEEDER != null">NUM_OF_SEEDER,</if>
		        <if test="COMPLETE != null">COMPLETE,</if>
		        RESOURCE_ID,
		        <if test="VIRTUAL_PEER_ID != null">VIRTUAL_PEER_ID,</if>
		        <if test="RELAY_SESSION_ID != null">RELAY_SESSION_ID,</if>
		        <if test="EXPIRES != null">EXPIRES,</if>
		        <if test="NETWORK_IP != null">NETWORK_IP,</if>
		        <if test="NETWORK_PORT != null">NETWORK_PORT,</if>
		        <if test="LINK != null">LINK,</if>
		        <if test="OVERLAY_NETWORK_ID != null">OVERLAY_NETWORK_ID,</if>
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        <if test="INDEX_URL != null">#{INDEX_URL},</if>
	   			#{REQUESTER_PEER_ID},                                        
		        #{ACTION_TYPE},
		        <if test="NOTIFICATION_ADDRESS != null">#{NOTIFICATION_ADDRESS},</if>
		        <if test="STORAGE_SIZE != null">#{STORAGE_SIZE},</if>
		        <if test="MAX_UP_BW != null">#{MAX_UP_BW},</if>
		        <if test="MAX_DN_BW != null">#{MAX_DN_BW},</if>
		        <if test="MAX_NUM_CONNECTION != null">#{MAX_NUM_CONNECTION},</if>
		        <if test="TIMEOUT != null">#{TIMEOUT},</if>
		        <if test="MAX_TRAFFIC != null">#{MAX_TRAFFIC},</if>
		        <if test="NUM_OF_SEEDER != null">#{NUM_OF_SEEDER},</if>
		        <if test="COMPLETE != null">#{COMPLETE},</if>
		        #{RESOURCE_ID},
		        <if test="VIRTUAL_PEER_ID != null">#{VIRTUAL_PEER_ID},</if>
		        <if test="RELAY_SESSION_ID != null">#{RELAY_SESSION_ID},</if>
		        <if test="EXPIRES != null">#{EXPIRES},</if>
		        <if test="NETWORK_IP != null">#{NETWORK_IP},</if>
		        <if test="NETWORK_PORT != null">#{NETWORK_PORT},</if>
		        <if test="LINK != null">#{LINK},</if>
		        <if test="OVERLAY_NETWORK_ID != null">#{OVERLAY_NETWORK_ID},</if>
		        now()
			</trim>
	</insert>
	
	<update id ="UPDATE_RESOURCE_ALLOCATION" parameterType="hashmap">
		UPDATE uprep_resource_allocation
		SET    
		        <if test="STORAGE_SIZE != null">STORAGE_SIZE = #{STORAGE_SIZE},</if>
		        <if test="MAX_UP_BW != null">MAX_UP_BW = #{MAX_UP_BW},</if>
		        <if test="MAX_DN_BW != null">MAX_DN_BW = #{MAX_DN_BW},</if>
		        <if test="MAX_NUM_CONNECTION != null">MAX_NUM_CONNECTION = #{MAX_NUM_CONNECTION},</if>
		        <if test="TIMEOUT != null">TIMEOUT = #{TIMEOUT},</if>
		        <if test="MAX_TRAFFIC != null">MAX_TRAFFIC = #{MAX_TRAFFIC},</if>
		        <if test="NUM_OF_SEEDER != null">NUM_OF_SEEDER = #{NUM_OF_SEEDER},</if>
		        <if test="COMPLETE != null">COMPLETE = #{COMPLETE},</if>
		        UPDATED_AT = now()
		<where>
			<trim prefixOverrides="AND">
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="VIRTUAL_PEER_ID != null">
					AND VIRTUAL_PEER_ID = #{VIRTUAL_PEER_ID}
				</if>
				<if test="RELAY_SESSION_ID != null">
					AND RELAY_SESSION_ID = #{RELAY_SESSION_ID}
				</if>
			</trim>
		</where>
	</update>
	
	<delete id="DELETE_RESOURCE_ALLOCATION" parameterType="hashmap" >
		DELETE FROM 
			uprep_resource_allocation
		<where>
			<trim prefixOverrides="AND">
				<if test="REQUESTER_PEER_ID != null">
					AND REQUESTER_PEER_ID = #{REQUESTER_PEER_ID}
				</if>
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="VIRTUAL_PEER_ID != null">
					AND VIRTUAL_PEER_ID = #{VIRTUAL_PEER_ID}
				</if>
				<if test="RELAY_SESSION_ID != null">
					AND RELAY_SESSION_ID = #{RELAY_SESSION_ID}
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
			</trim>
		</where> 
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/network/mp2p/moms/OMS/kr/re/etri/uprep/shared/mapper/ResourcePoolMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_RESOURCE_POOL_ALLOCATION" parameterType="hashmap" resultType="hashmap">
		SELECT  RESOURCE_ID,
				OMS_URL,
	   			TYPE,                                        
		        IP_ADDRESS,
		        PORT,
		        CS_URL,
		        EXPIRES
		FROM     
				uprep_resource_pool
		<where>
			<trim prefixOverrides="AND">
				<if test="TYPE != null">
					AND TYPE = #{TYPE}
				</if>
				<if test="STORAGE_SIZE != null">
					AND STORAGE_SIZE <![CDATA[>=]]> #{STORAGE_SIZE}
				</if>
				<if test="MAX_UP_BW != null">
					AND MAX_UP_BW <![CDATA[>=]]> #{MAX_UP_BW}
				</if>
				<if test="MAX_DN_BW != null">
					AND MAX_DN_BW <![CDATA[>=]]> #{MAX_DN_BW}
				</if>
				<if test="MAX_NUM_CONNECTION != null">
					AND MAX_NUM_CONNECTION <![CDATA[>=]]> #{MAX_NUM_CONNECTION}
				</if>
					AND MAX_NUM_OVERLAY_NETWORK <![CDATA[>]]> 0
			</trim>
		</where>
	</select>
	
	<select id="SELECT_RESOURCE_POOL" parameterType="hashmap" resultType="hashmap">
		SELECT  RESOURCE_ID,
				OMS_URL,
	   			TYPE,                                        
		        IP_ADDRESS,
		        PORT,
		        CS_URL,
		        EXPIRES,
		        STORAGE_SIZE,
		        MAX_UP_BW,
	            MAX_DN_BW,
		        MAX_NUM_CONNECTION,
		        MAX_NUM_OVERLAY_NETWORK,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT,
		        DATE_FORMAT(UPDATED_AT, '%Y-%m-%d %H:%i:%s') UPDATED_AT                                  
		FROM     
				uprep_resource_pool
		<where>
			<trim prefixOverrides="AND">
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="TYPE != null">
					AND TYPE = #{TYPE}
				</if>
				<if test="IP_ADDRESS != null">
					AND IP_ADDRESS = #{IP_ADDRESS}
				</if>
				<if test="PORT != null">
					AND PORT = #{PORT}
				</if>
				<if test="CS_URL != null">
					AND CS_URL = #{CS_URL}
				</if>
				<if test="OMS_URL != null">
					AND OMS_URL = #{OMS_URL}
				</if>
			</trim>
		</where>
	</select>
	
	
	<select id="SELECT_LAST_INSERT_RESOURCE_ID" parameterType="hashmap" resultType="hashmap">
		SELECT  RESOURCE_ID,
				OMS_URL,
	   			TYPE,                                        
		        IP_ADDRESS,
		        PORT,
		        CS_URL,
		        EXPIRES,
		        STORAGE_SIZE,
		        MAX_UP_BW,
	            MAX_DN_BW,
		        MAX_NUM_CONNECTION,
		        MAX_NUM_OVERLAY_NETWORK
		FROM     
				uprep_resource_pool
		ORDER BY 
				CREATED_AT DESC 
		LIMIT 1
	</select>
	
	<insert id="INSERT_RESOURCE_POOL" parameterType="hashmap">
		INSERT INTO uprep_resource_pool
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        RESOURCE_ID,
		        OMS_URL,
	   			TYPE,                                        
		        <if test="IP_ADDRESS != null">IP_ADDRESS,</if>
		        <if test="PORT != null">PORT,</if>
		        CS_URL,
		        EXPIRES,
		        <if test="STORAGE_SIZE != null">STORAGE_SIZE,</if>
		        MAX_UP_BW,
	            MAX_DN_BW,
		        MAX_NUM_CONNECTION,
		        MAX_NUM_OVERLAY_NETWORK,
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{RESOURCE_ID},
		        #{OMS_URL},
	   			#{TYPE},                                        
		        <if test="IP_ADDRESS != null">#{IP_ADDRESS},</if>
		        <if test="PORT != null">#{PORT},</if>
		        #{CS_URL},
		        #{EXPIRES},
		        <if test="STORAGE_SIZE != null">#{STORAGE_SIZE},</if>
		        #{MAX_UP_BW},
	            #{MAX_DN_BW},
		        #{MAX_NUM_CONNECTION},
		        #{MAX_NUM_OVERLAY_NETWORK},
		        now()
			</trim>
		ON 
			DUPLICATE KEY 
		UPDATE
			TYPE = #{TYPE} , 
			EXPIRES = #{EXPIRES} ,
			<if test="STORAGE_SIZE != null"> STORAGE_SIZE = #{STORAGE_SIZE} ,</if> 
			MAX_UP_BW = #{MAX_UP_BW} ,
			MAX_DN_BW = #{MAX_DN_BW} ,
			MAX_NUM_CONNECTION = #{MAX_NUM_CONNECTION} ,
			MAX_NUM_OVERLAY_NETWORK = #{MAX_NUM_OVERLAY_NETWORK} ,
			UPDATED_AT = now()
	</insert>
	
	<update id ="UPDATE_RESOURCE_POOL" parameterType="hashmap">
		UPDATE uprep_resource_pool
		SET    
	        TYPE = #{TYPE} , 
			EXPIRES = #{EXPIRES} ,
			<if test="STORAGE_SIZE != null"> STORAGE_SIZE = #{STORAGE_SIZE} ,</if> 
			MAX_UP_BW = #{MAX_UP_BW} ,
			MAX_DN_BW = #{MAX_DN_BW} ,
			MAX_NUM_CONNECTION = #{MAX_NUM_CONNECTION} ,
			MAX_NUM_OVERLAY_NETWORK = #{MAX_NUM_OVERLAY_NETWORK} ,
			UPDATED_AT = now()
		WHERE  
			RESOURCE_ID = #{RESOURCE_ID}
	</update>
	
	<delete id="DELETE_RESOURCE_POOL" parameterType="hashmap" >
		DELETE FROM 
			uprep_resource_pool
		<where>
			<trim prefixOverrides="AND">
				<if test="RESOURCE_ID != null">
					AND RESOURCE_ID = #{RESOURCE_ID}
				</if>
				<if test="OMS_URL != null">
					AND OMS_URL = #{OMS_URL}
				</if>
			</trim>
		</where> 
	</delete>
	
	<delete id="DELETE_ALL_RESOURCE_POOL" parameterType="hashmap" >
		DELETE FROM 
			uprep_resource_pool
		<where>
			<trim prefixOverrides="AND">
				<if test="OMS_URL != null">
					AND OMS_URL LIKE CONCAT('%',#{OMS_URL},'%')
				</if>
				<if test="IP_ADDRESS != null">
					AND IP_ADDRESS = #{IP_ADDRESS}
				</if>
				<if test="CS_URL != null">
					AND CS_URL LIKE CONCAT('%',#{CS_URL},'%')
				</if>
			</trim>
		</where>
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/mapper/FileMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_FILE" parameterType="hashmap" resultType="hashmap">
		SELECT  FILE_ID,
	   			CHANNEL_ID,                                        
		        FILENAME,
		        FILE_SIZE,
		        DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT                                   
		FROM     
				uprep_file
		WHERE
				CHANNEL_ID = #{CHANNEL_ID}
	</select>
	
	<insert id="INSERT_FILE" parameterType="hashmap">
		INSERT INTO uprep_file
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        FILE_ID,
	   			CHANNEL_ID,                                        
		        FILENAME,
		        FILE_SIZE,
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{FILE_ID},
	   			#{CHANNEL_ID},                                        
		        #{FILENAME},
		        #{FILE_SIZE},
		        now()
			</trim>
	</insert>
	
	<update id ="UPDATE_FILE" parameterType="hashmap">
		UPDATE uprep_file
		SET    
		       <if test="CHANNEL_ID != null">CHANNEL_ID = #{CHANNEL_ID},</if>
		       <if test="FILENAME != null">FILENAME = #{FILENAME},</if>
		       <if test="FILE_SIZE != null">FILE_SIZE = #{FILE_SIZE},</if>
		       CREATED_AT = now()
		WHERE  
			CHANNEL_ID = #{CHANNEL_ID}
		AND
			FILE_ID = #{FILE_ID}
	</update>
	
	<delete id="DELETE_FILE" parameterType="hashmap" >
		DELETE FROM 
			uprep_file
		WHERE
				CHANNEL_ID = #{CHANNEL_ID} 
	</delete>
	
	<delete id="DELETE_ALL_FILE" parameterType="hashmap" >
		DELETE FROM 
			uprep_file
		<where>
			<if test="CHANNEL_ID_LIST != null">
			CHANNEL_ID IN
				<foreach collection="CHANNEL_ID_LIST" item="item" separator="," open="(" close=")">
				    #{item}
				</foreach>
			</if>
		</where>
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/mapper/OverlayNetworkMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	<select id="SELECT_INDEX_URL" parameterType="hashmap" resultType="hashmap">
		SELECT  
				DISTINCT INDEX_URL
		FROM     
				uprep_overlay_network
		WHERE 
				INDEX_URL IS NOT NULL
	</select>
	
	<select id="SELECT_OVERLAY_NETWORK" parameterType="java.util.HashMap" resultType="java.util.HashMap">
		SELECT   OVERLAY_NETWORK_ID,                                        
		         VERSION,
		         OWNER_ID,
		         INDEX_URL,
		         EXPIRES,
		         PAM_ENABLED,
		         PAMS_URL,  
		         PAM_INTERVAL,    
		         CLOSED,
		         AUTH_KEY,
		         OMS_VP_CNT,
		         DATE_FORMAT(CREATED_AT, '%Y-%m-%d %H:%i:%s') CREATED_AT,
		         DATE_FORMAT(UPDATED_AT, '%Y-%m-%d %H:%i:%s') UPDATED_AT                                  
		FROM     
				 uprep_overlay_network
		<where>
			<trim prefixOverrides="AND">
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="OWNER_ID != null">
					AND OWNER_ID = #{OWNER_ID}
				</if>
				<if test="INDEX_URL != null">
					AND INDEX_URL LIKE CONCAT('%',#{INDEX_URL},'%')
				</if>
			</trim>
		</where>
	</select>
	
	
	<insert id="INSERT_OVERLAY_NETWORK" parameterType="hashmap">
		INSERT INTO uprep_overlay_network
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
	   			OVERLAY_NETWORK_ID,                                        
		        VERSION,
		        OWNER_ID,
		        EXPIRES,
		        PAM_ENABLED,
		        <if test="INDEX_URL != null">INDEX_URL,</if>  
		        <if test="PAMS_URL != null">PAMS_URL,</if>  
		        <if test="PAMS_INTERVAL != null">PAM_INTERVAL,</if>      
		        <if test="CLOSED != null">CLOSED</if>,
		        <if test="AUTH_KEY != null">AUTH_KEY,</if>  
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
	   			#{OVERLAY_NETWORK_ID},                                        
		        #{VERSION},
		        #{OWNER_ID},
		        #{EXPIRES},
		        #{PAM_ENABLED},
		        <if test="INDEX_URL != null">#{INDEX_URL},</if> 
		        <if test="PAMS_URL != null">#{PAMS_URL},</if>  
		        <if test="PAMS_INTERVAL != null">#{PAM_INTERVAL},</if>      
		        <if test="CLOSED != null">#{CLOSED},</if>
		        <if test="AUTH_KEY != null">#{AUTH_KEY},</if>  
	   			NOW()
			</trim>
	</insert>
	
	<update id ="UPDATE_OVERLAY_NETWORK" parameterType="hashmap">
		UPDATE uprep_overlay_network
		SET    VERSION = #{VERSION},
			   <if test="INDEX_URL != null">INDEX_URL = #{INDEX_URL},</if>
		       <if test="EXPIRES != null">EXPIRES = #{EXPIRES},</if>
		       <if test="CLOSED != null">CLOSED = #{CLOSED},</if>
		       <if test="AUTH_KEY != null">AUTH_KEY = #{AUTH_KEY},</if>
		       UPDATED_AT = now()
		WHERE  
			OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
	</update>
	
	<update id ="UPDATE_PAM_CONF_OVERLAY_NETWORK" parameterType="hashmap">
		UPDATE uprep_overlay_network
		SET    PAM_ENABLED = #{PAM_ENABLED},
			   <if test="PAMS_URL != null">PAMS_URL = #{PAMS_URL},</if>
		       <if test="PAM_INTERVAL != null">PAM_INTERVAL = #{PAM_INTERVAL},</if>
		       UPDATED_AT = now()
		WHERE  
			OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
	</update>
	
	<update id ="UPDATE_VIRTUAL_PEER_COUNT_OVERLAY_NETWORK" parameterType="hashmap">
		UPDATE uprep_overlay_network
		SET    
			   <if test="INCREASE == true">OMS_VP_CNT = OMS_VP_CNT + 1</if>
		       <if test="INCREASE == false">OMS_VP_CNT = OMS_VP_CNT - 1</if>
		WHERE  
			OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
	</update>
	
	<delete id="DELETE_OVERLAY_NETWORK" parameterType="hashmap" >
		DELETE FROM 
			uprep_overlay_network 
		WHERE 
			OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
	</delete>
	
	<delete id="DELETE_ALL_OVERLAY_NETWORK" parameterType="hashmap" >
		DELETE FROM 
			uprep_overlay_network 
		<where>
			<trim prefixOverrides="AND">
				<if test="OWNER_ID != null">
					AND OWNER_ID LIKE CONCAT('%',#{OWNER_ID},'%')
				</if>
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="INDEX_URL != null">
					AND INDEX_URL LIKE CONCAT('%',#{INDEX_URL},'%')
				</if>
			</trim>
		</where>
	</delete>
	
</mapper>

=== ITU-T-SG11-Q8/Q.4102/oms/OMS/kr/re/etri/uprep/shared/mapper/PeerMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
       PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
       "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="kr.re.etri.uprep">
	
	
	<select id="SELECT_PEER_COUNT" parameterType="hashmap" resultType="hashmap">
		SELECT  COUNT(*) CNT                                   
		FROM     
				uprep_peer
		WHERE
				OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
	</select>
	
	<select id="SELECT_PEER" parameterType="hashmap" resultType="hashmap">
		SELECT  PEER_ID,
	   			OVERLAY_NETWORK_ID,                                        
		        IP_ADDRESS,
		        PORT,
		        PUBLIC                                   
		FROM     
				uprep_peer
		<where>
			<trim prefixOverrides="AND">
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="PEER_ID != null">
					AND PEER_ID = #{PEER_ID}
				</if>
			</trim>
		</where>
	</select>
	
	<insert id="INSERT_PEER" parameterType="hashmap">
		INSERT INTO uprep_peer
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        PEER_ID,
	   			OVERLAY_NETWORK_ID,                                        
		        IP_ADDRESS,
		        PORT,
		        PUBLIC,
		        CREATED_AT
			</trim>
		VALUES
			<trim prefix="(" prefixOverrides="" suffix=")" suffixOverrides=",">
		        #{PEER_ID},
	   			#{OVERLAY_NETWORK_ID},                                        
		        #{IP_ADDRESS},
		        #{PORT},
		        #{PUBLIC},
		        now()
			</trim>
		ON 
			DUPLICATE KEY 
		UPDATE
			IP_ADDRESS = #{IP_ADDRESS} , 
			PORT = #{PORT} , 
			PUBLIC = #{PUBLIC} ,
			UPDATED_AT = now()
	</insert>
	
	<update id ="UPDATE_PEER" parameterType="hashmap">
		UPDATE uprep_peer
		SET    
		       <if test="IP_ADDRESS != null">IP_ADDRESS = #{IP_ADDRESS},</if>
		       <if test="PORT != null">PORT = #{PORT},</if>
		       <if test="PUBLIC != null">PUBLIC = #{PUBLIC},</if>
		       UPDATED_AT = now()
		WHERE  
			OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
		AND 
			PEER_ID = #{PEER_ID}
	</update>
	
	<delete id="DELETE_PEER" parameterType="hashmap" >
		DELETE FROM 
			uprep_peer
		<where>
			<trim prefixOverrides="AND">
				<if test="OVERLAY_NETWORK_ID != null">
					AND OVERLAY_NETWORK_ID = #{OVERLAY_NETWORK_ID}
				</if>
				<if test="PEER_ID != null">
					AND PEER_ID = #{PEER_ID}
				</if>
			</trim>
		</where> 
	</delete>
	
	<delete id="DELETE_ALL_PEER" parameterType="hashmap" >
		DELETE FROM 
			uprep_peer
		<where>
			<if test="OVERLAY_ID_LIST != null">
			OVERLAY_NETWORK_ID IN
				<foreach collection="OVERLAY_ID_LIST" item="item" separator="," open="(" close=")">
				    #{item}
				</foreach>
			</if>
		</where>
	</delete>
	
</mapper>
